#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

DATA_DIR="/etc/rustdesk"
HBBS_BIN="/etc/rustdesk/go-rustdesk-server"

start_service() {
    procd_open_instance "go-rustdesk-server"
    procd_set_param command sh -c "cd '$DATA_DIR' && '$GORS_BIN' "
    procd_set_param cwd "$DATA_DIR"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param env RUST_LOG=debug
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "rsop"
}
