#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1

DATA_DIR="/etc/rustdesk"
RSOP_BIN="$DATA_DIR/rsop"
HBBS_BIN="$DATA_DIR/hbbs"
HBBR_BIN="$DATA_DIR/hbbr"

start_service() {
    procd_open_instance "rsop"
    procd_set_param command sh -c "cd '$DATA_DIR' && exec '$RSOP_BIN'"
    procd_set_param respawn 3600 3 3
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance

    procd_open_instance "hbbs"
    procd_set_param command sh -c "cd '$DATA_DIR' && exec '$HBBS_BIN'"
    procd_set_param respawn 3600 3 3
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance

    procd_open_instance "hbbr"
    procd_set_param command sh -c "cd '$DATA_DIR' && exec '$HBBR_BIN'"
    procd_set_param respawn 3600 3 3
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "rsop"
}
