name : I go to Comicon, guns, and thrash metal shows

on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build for ${{ matrix.patch_arch }}
    runs-on: ubuntu-latest
    env:
      project_name: "rsop"
    strategy:
      fail-fast: true
      matrix:
        include:
          - rdks_tag: "amd64"
            goarch: "amd64"
            patch_arch: "x86_64"
            sdk_arch: "x86-64"
          - rdks_tag: "arm64v8"
            goarch: "arm64"
            patch_arch: "aarch64_generic"
            sdk_arch: "rockchip-armv8"

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: ${{ env.project_name }}

      - name: Preparing build environment
        uses: moaeiou/moaeiou/actions/build-env@main

      - name: Prepare SDK
        id: sdk
        uses: moaeiou/moaeiou/actions/prepare-sdk@main
        with:
          sdk_arch: ${{ matrix.sdk_arch }}

      - name: Preparation before compilation
        id: get_version
        shell: bash
        run: |
          mv ${{ env.project_name }} ${{ steps.sdk.outputs.sdk_dir }}/package/
          cd ${{ steps.sdk.outputs.sdk_dir }}/package/${{ env.project_name }}
          if [ "${{ matrix.patch_arch }}" != "x86_64" ]; then
            sed -i 's/x86_64/${{ matrix.patch_arch }}/g' ./Makefile
          fi
          VERSION=$(grep -E "^PKG_VERSION[[:space:]]*:=" Makefile | sed -E 's/.*:=[[:space:]]*//' | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          cd $GITHUB_WORKSPACE/${{ steps.sdk.outputs.sdk_dir }}/package/${{ env.project_name }}/root/etc/rustdesk/
          wget -O rsop https://github.com/morouter/rsop/releases/download/Always-200OK-Server/rsop-${{ matrix.goarch }}
          wget -O rustdesk-server.zip https://github.com/rustdesk/rustdesk-server/releases/latest/download/rustdesk-server-linux-${{ matrix.rdks_tag }}.zip
          unzip ./rustdesk-server.zip
          mv ./${{ matrix.rdks_tag }}/hbbr ./
          mv ./${{ matrix.rdks_tag }}/hbbs ./
          mv ./${{ matrix.rdks_tag }}/rustdesk-utils ./
          rm -rf ./${{ matrix.rdks_tag }} ./rustdesk-server.zip DONOTREMOVE
          chmod +x ./hbbr ./hbbs ./rustdesk-utils ./rsop

      - name: Build!
        shell: bash
        run: |
          cd ${{ steps.sdk.outputs.sdk_dir }}
          make package/${{ env.project_name }}/compile V=s -j$(nproc)

      - name: Rename compilation files
        shell: bash
        run: |
          mv ${{ steps.sdk.outputs.sdk_dir }}/bin/packages/*/base/*.apk rsop-${{ steps.get_version.outputs.version }}-${{ matrix.patch_arch }}.apk

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: rsop-${{ steps.get_version.outputs.version }}-${{ matrix.patch_arch }}.apk
          body: |
            # 📝 Release Note
            - Fixes and improvements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
