name : I go to Comicon, guns, and thrash metal shows

on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build for ${{ matrix.patch_arch }}
    runs-on: ubuntu-latest
    env:
      project_name: "rsop"
    strategy:
      fail-fast: false
      matrix:
        include:
          - tags: "amd64-musl"
            patch_arch: "x86_64"
            sdk_name: "openwrt-sdk-x86-64_gcc-14.3.0_musl.Linux-x86_64"
          - tags: "arm64-musl"
            patch_arch: "aarch64_generic"
            sdk_name: "openwrt-sdk-rockchip-armv8_gcc-14.3.0_musl.Linux-x86_64"

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Preparing build environment
        uses: mokanove/mokanove/actions/build-env@main

      - name: Prepare SDK
        uses: mokanove/mokanove/actions/prepare-sdk@main
        with:
          sdk_name: ${{ matrix.sdk_name }}

      - name: Clone Source Code
        uses: mokanove/mokanove/actions/clone@main
        with:
          sdk_name: ${{ matrix.sdk_name }}
          project_name: ${{ env.project_name }}

      - name: Get Version
        id: get_version
        shell: bash
        run: |
          cd ${{ matrix.sdk_name }}/package/${{ env.project_name }}
          VERSION=$(grep -E "^PKG_VERSION[[:space:]]*:=" Makefile | sed -E 's/.*:=[[:space:]]*//' | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Change Arch
        shell: bash
        run: |
          cd ${{ matrix.sdk_name }}/package/${{ env.project_name }}
          if [ "${{ matrix.patch_arch }}" != "x86_64" ]; then
            sed -i 's/x86_64/${{ matrix.patch_arch }}/g' ./Makefile
          fi

      - name: Preparation before compilation
        shell: bash
        run: |
            cd ${{ matrix.sdk_name }}/package/${{ env.project_name }}/root/etc/rustdesk
            rm DONOTREMOVE
            wget -O go-rustdesk-server "https://github.com/mokanove/go-rustdesk-server/releases/latest/download/go-rustdesk-server-linux-${{ matrix.tags }}"
            chmod +x ./go-rustdesk-server

      - name: Build!
        uses: mokanove/mokanove/actions/build@main
        with:
          sdk_name: ${{ matrix.sdk_name }}
          project_name: ${{ env.project_name }}

      - name: Rename compilation files
        shell: bash
        run: |
            mv ${{ matrix.sdk_name }}/bin/packages/*/base/rsop* $GITHUB_WORKSPACE/rsop-${{ steps.get_version.outputs.version }}-${{ matrix.patch_arch }}.apk

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: ${{ github.workspace }}/*.apk
          body: |
            # 📝 Release Notes
            - Fixed the issue of insufficient permissions for go-rustdesk-server.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
