name : I go to Comicon, guns, and thrash metal shows

on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build for ${{ matrix.patch_arch }}
    runs-on: ubuntu-latest
    env:
      project_name: "rsop"
    strategy:
      fail-fast: false
      matrix:
        include:
          - gordks_tag: "amd64-musl"
            rdks_tag: "amd64"
            patch_arch: "x86_64"
            sdk_name: "openwrt-sdk-x86-64_gcc-14.3.0_musl.Linux-x86_64"
          - gordks_tag: "arm64-musl"
            rdks_tag: "arm64v8"
            patch_arch: "aarch64_generic"
            sdk_name: "openwrt-sdk-rockchip-armv8_gcc-14.3.0_musl.Linux-x86_64"

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: ${{ env.project_name }}

      - name: Preparing build environment
        uses: mokanove/mokanove/actions/build-env@main

      - name: Prepare SDK
        uses: mokanove/mokanove/actions/prepare-sdk@main
        with:
          sdk_name: ${{ matrix.sdk_name }}

      - name: Preparation before compilation
        id: get_version
        shell: bash
        run: |
          mv ${{ env.project_name }} ${{ matrix.sdk_name }}/package/
          cd ${{ matrix.sdk_name }}/package/${{ env.project_name }}
          if [ "${{ matrix.patch_arch }}" != "x86_64" ]; then
            sed -i 's/x86_64/${{ matrix.patch_arch }}/g' ./Makefile
          fi
          VERSION=$(grep -E "^PKG_VERSION[[:space:]]*:=" Makefile | sed -E 's/.*:=[[:space:]]*//' | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          cd $GITHUB_WORKSPACE/${{ matrix.sdk_name }}/package/${{ env.project_name }}/root/etc/rustdesk
          rm DONOTREMOVE
          wget -O go-rustdesk-server https://github.com/mokanove/go-rustdesk-server/releases/download/V2.1.6/go-rustdesk-server-linux-${{ matrix.gordks_tag }}
          chmod +x ./go-rustdesk-server
          wget -O rustdesk-server.zip https://github.com/rustdesk/rustdesk-server/releases/download/1.1.15/rustdesk-server-linux-${{ matrix.rdks_tag }}.zip
          sudo apt-get update
          sudo apt-get install unzip -y
          unzip ./rustdesk-server.zip
          mv ./${{ matrix.rdks_tag }}/* ./
          rm -rf ./${{ matrix.rdks_tag }}
          chmod +x ./hbbr
          chmod +x ./hbbs
          chmod +x ./rustdesk-utils

      - name: Build!
        shell: bash
        run: |
          cd ${{ matrix.sdk_name }}
          make package/${{ env.project_name }}/compile V=s -j$(nproc)

      - name: Rename compilation files
        shell: bash
        run: |
          mv ${{ matrix.sdk_name }}/bin/packages/*/base/*.apk rsop-${{ steps.get_version.outputs.version }}-${{ matrix.patch_arch }}.apk

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: rsop-${{ steps.get_version.outputs.version }}-${{ matrix.patch_arch }}.apk
          body: |
            # 📝 Release Note
            - Fixes and improvements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
