name: NEVER USING RUST
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build for ${{ matrix.patch_arch }}
    runs-on: ubuntu-latest
    env:
      project_name: "rsop"
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            runs-on: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config libssl-dev libsodium-dev \
            libsqlite3-dev musl-tools cmake perl

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build binary
        env:
          OPENSSL_STATIC: "1"
          OPENSSL_VENDORED: "1"
        run: |
          git clone https://github.com/rustdesk/rustdesk-server.git
          cd rustdesk-server
          git checkout dependabot/submodules/master/libs/hbb_common-387603f
          git pull
          git submodule update --init --recursive
          cargo build --release --target ${{ matrix.target }} --bins
          ls -al target/${{ matrix.target }}/release/
