name: NEVER USING RUST
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build for ${{ matrix.patch_arch }}
    runs-on: ubuntu-latest
    env:
      project_name: "rsop"
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            runs-on: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config libssl-dev libsodium-dev \
            libsqlite3-dev musl-tools cmake perl

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build x86_64
        if: matrix.target == 'x86_64-unknown-linux-musl'
        env:
          OPENSSL_STATIC: "1"
          OPENSSL_VENDORED: "1"
        run: |
          cd rustdesk-server
          cargo build --release --target x86_64-unknown-linux-musl --bins

      - name: Build aarch64
        if: matrix.target == 'aarch64-unknown-linux-musl'
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu
          cd rustdesk-server
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc \
          OPENSSL_STATIC=1 \
          OPENSSL_VENDORED=1 \
          cargo build --release --target aarch64-unknown-linux-musl --bins
